import Pages from 'imp/styles/statement.module.css'
import styles from 'imp/styles/Customs.module.css'
import intro from 'imp/styles/Intro.module.css'
import CusStyle from 'imp/styles/Customs.module.css'
import Link from 'next/link';
import { useState } from 'react';
export default function LastChance2(){

    return(
        <>
            <div class={Pages.main}>
            <hr width ="100%" align = "center" size="1"></hr><br></br>
            <h2>Crew from the Evolutionary Level Above Human Offers -</h2>
            <h1>LAST CHANCE TO ADVANCE BEYOND HUMAN</h1><br></br>
            <hr width ="100%" align = "center" size="1"></hr>
            <h4>The following statements could sound very presumptuous. However, these facts can come into focus or "prove" themselves if they are seriously explored a step at a time. They could also sound very "doomsdayish." Though, in truth, they may be the most joyous "sound of music" to the ears and eyes of those who have been waiting for them.</h4>
            <hr width ="100%" align = "center" size="1"></hr>
            <br></br>
            <p>The Earth's present "civilization" is about to be recycled - "spaded under" - in order that the planet might be refurbished. The human "weeds" have taken over the garden and disturbed its usefulness beyond repair.
            <br></br> The human kingdom was designed (created) as a stepping stone between the animal kingdom and the Evolutionary Kingdom Level Above Human (the true Kingdom of God).
            <br></br> It is the soul that can progress from the human kingdom to the Kingdom Level Above Human. Both kingdom levels have their own unique physical "containers" (bodies) for the souls that reside in that kingdom level.
            <br></br><br></br>As the human goes out to "choose" servants from within the animal kingdom, from beasts of burden to seeing-eye dogs - if that animal grows to find pleasure only in serving its master, no longer identifies as an animal, but sees itself as a family member in that human family, and its behavior is pleasing to that human - the two become bound together. The human family then provides the body (a human infant) for that soul to enter, allowing it to move up into the human evolutionary kingdom. (This is not to suggest that all humans are containers for souls moving up from the animal kingdom, for most humans are containers for human kingdom returnees still bound to that family unit.)
            <br></br>
            <br></br> In a more realistic way, periodically a Member of the Kingdom Level Above Human receives instruction to incarnate among humans to seek out the souls that have been "tagged" or given a "deposit" (an "implant") of knowledge concerning the TRUTH about the Evolutionary Level Above Human. That knowledge finds each recipient wanting to "separate from the pack," and prepares him to recognize the Teacher or Representatives sent from the Kingdom Level Above Human. When he/she connects with that Teacher - an "Older Member" in that Kingdom - he is then offered further instruction in knowledge and behavior that can open the door of service to him. If that human changes to the degree that he no longer desires any human behavior and he pleases that Member of the Kingdom Level Above Human, a bond is formed between them and a body belonging to that new Kingdom is provided for that soul to move up into.
            Both the human kingdom and the Kingdom Level Above Human - the true Kingdom of God - are physical and biological. However, the human kingdom is made up of mammalian bodies - "seed-bearing" plants or "containers" - while the Kingdom Level Above Human is made up of non-mammalian, non-seed-bearing bodies or containers for souls. The Kingdom Level Above Human's "children," or young, are those who have graduated from the human kingdom under the tutorship (midwifing) of a Member of the true Kingdom of God who has been through that transition - bonded to His Father - at a previous time.
            A "student" or prospective "child" of a Member of the Level Above Human can, with the help of his Older Member(s) from that Kingdom Level, overcome or rise out of all human-mammalian behavior - sexuality and gender consciousness - and all other addictions and ties of the human kingdom. Older Members, as experienced "clinicians," are necessary to take souls through this "weaning" - this difficult "withdrawal" from humanness and binding "misinformation" concepts. The student must complete this change to the point of abhorring human behavior before his soul can become a "match" with a biological body of the true Kingdom of God - for that new, genderless body is designed to function at a far more refined level.
            The Evolutionary Level Above Human, the true Kingdom of God, the "Headquarters" of all that is, is a many-membered Kingdom which physically exists in the highest, most distant Heaven - a non-temporal place (outside of time, and therefore with eternal life). It is the only place from which souls, life, and all creating originates. Being non-temporal, it was, is, and forever will be - a concept that temporal creatures are not designed to comprehend. This "Next Level" Kingdom designed the "temporal" world outside its "borders" and designed temporal creatures for souls to inhabit while in the human "classroom." If the soul survives and moves forward through all its tests along the way - it can, with the help of a Member of the Level Above Human, lose its temporal characteristics and become a part of their non-perishable, non-corruptible world. However, all other souls who reach a certain degree of corruption (having of their own free will chosen to become totally separate from their Creator, whether knowingly or not) will engage a "self-destruct" mechanism at the Age's end.

            <br></br> The term "TRUE" Kingdom of God is used repeatedly because there are many space alien races that through the centuries of this civilization (and in civilizations prior) have represented themselves to humans as "Gods." We refer to them collectively as "space alien races in opposition to the Next Level," what historically have been referred to as "Luciferians," for their ancestors fell into disfavor with the Kingdom Level Above Human many thousands of years ago. They are not genderless - they still need to reproduce. They have become nothing more than technically advanced humans (clinging to human behavior) who retained some of what they learned while in the early training of Members of the Level Above Human, e.g., having limited: space-time travel, telepathic communication, advanced travel hardware (spacecrafts, etc.), increased longevity, advanced genetic engineering, and such skills as suspending holograms (as used in some so-called "religious miracles"). The Next Level - the true Kingdom of God - has the only truly advanced space-time travel vehicles, or spacecrafts, and is not interested in creating phenomena (signs) or impressive trickery.
            These malevolent space races are the humans' GREATEST ENEMY. They hold humans in unknown slavery only to fulfill their own desires. They cannot "create," though they develop races and biological containers through genetic manipulation and hybridization. They even try to "make deals" with human governments to permit them (the space aliens) to engage in biological experimentation (through abductions) in exchange for such things as technically advanced modes of travel - though they seldom follow through, for they don't want the humans of this civilization to become another element of competition. They war among themselves over the spoils of this planet and use religion and increased sexual behavior to keep humans "drugged" and ignorant (in darkness) while thinking they are in "God's" keeping. They use the discarnate (spirit) world to keep humans preoccupied with their addictions. These negative space races see to it, through the human "social norm" (the largest Luciferian "cult" there is), that man continues to not avail himself of the possibility of advancing beyond human.
            Just as the biological body is the "container" for the soul, the soul is the "container" for Mind ("Spirit"). Mind translates into the brain as information (knowledge). Information is available to humans from only two sources - the mind of the adversarial space races - or the Mind of the Kingdom Level Above Human. The mind of the adversarial space races yields misinformation (promoting the behavior and concepts of this corrupt world). The Mind from the true Kingdom of God yields true information (though the space races and their servants would reverse this interpretation). As we change, in the progression of overcoming humanness - the percentages change - of which mind occupies our soul - Truth increases as misinformation decreases. If one chooses to revert back to humanness, the process reverses - the Truth is aborted as the soul becomes more filled with mammalian mind. [The word "True" or "Truth" is defined as the most accurate perception available at any given level of understanding, changing at the level of the eye of the beholder.] That Next Level Truth can even be taken from us if we abuse it. When our "eye becomes single" or our soul is filled only with the Mind or "Spirit" from the true Kingdom of God, it becomes pure or "Holy" Mind ("Spirit").
            The design of the true Kingdom of God permits the presence of an adversial element during a human civilization as the primary catalyst for growth. Without it, we would have no choices - our free will could not be exercised. Our right choices are what find us in alignment to receive a "deposit" of recognition when the Truth is offered.
            <br></br><br></br><hr width ="100%" align = "center" size="1"></hr>
            <br></br> Two thousand years ago, the Kingdom Level Above Human appointed an Older Member to send a Representative (His "Son"), along with some of their beginning students, to incarnate on this garden. (These students had brief periods of association with and guidance from Members of the Kingdom Level Above Human during the early generations of this civilization.) While on Earth as an "away team" with their "Captain," they were to work on their overcoming of humanness and tell the civilization they were visiting how the true Kingdom of God can be entered. The humans under the control of the adverserial space races killed the "Captain" and His crew, because of the "blasphemous" position they held, and quickly turned the teachings of the "Captain" (the Older Member's "Son") into watered-down Country Club religion - obscuring the remnants of the Truth.
            Again an "away team" from the Level Above Human incarnated in the 1970's in the mature (adult) bodies that had been picked and prepped for this current mission. This time the "Admiral" (the Older Member, or "Father," incarnate in a female vehicle) came with the "Captain" and his crew. As the two Older Members put out a "statement" and held public meetings over about a 9-month period in 1975-76 to bring their crew together, the media tagged them the "UFO cult" because of their expectation of leaving aboard a spacecraft ("cloud of light") at the completion of their "overcoming." The two Older Members then went into seclusion with their crew (students), "lifting them out" of the world for almost 17 years (not accepting any new students), making Earth's surface their classroom. This isolation was absolutely necessary, for the degree of their overcoming of sexuality, addictions, and ties to the human environment has to be taken to the point of matching the minimum behavior and consciousness requirements of the Kingdom Level Above Human. Only then would their new "Next Level" bodies be functional. They resurfaced briefly for about a 3-1/2-month period in 1992, allowing some of their "dropouts" to rejoin them.
            This changeover (sufficient "overcoming" to inherit Next Level bodies) is nearing completion, and before this "away team" returns, representatives of the "Class" are instructed to put this information before the public. The Next Level will determine the future of each individual soul according to its response to this information and the Next Level's Representatives.
            These space alien adversaries, for the most part, are about to be "recycled" as this human civilization is "spaded." They know that "rumor has it" that their days are numbered. They refuse to believe it and are desperate to recruit souls from the human kingdom into their "heavenly kingdom." There are many "counterfeit" heavens, and each "heaven" is at this time collecting "names in their book," forcing a stand of allegiance, polarizing each individual's commitment to his chosen "God."
            When Members of the Level Above Human are physically present, the opposing forces work the hardest against them in order to support their own position. They do almost anything to keep humans from following the path toward the Evolutionary Level Above Human. They "turn up the heat" at this time in the area of mammalian behavior, primarily sexuality and the family. This has become such an overwhelming presence in the Earth's atmosphere that even some of the crew that came with us were lost to its temptation. Don't forget that when the adversaries were expelled, they had to condemn the true Kingdom of God in order to support their own desires, and see it simply as another path - inhumane and radically uncompromising.
            When this present "away team" leaves (which will be very soon), the Truth will go with them. You cannot preserve the Truth in your religions. It is present only as long as a Truth bearer (Older Member from the true Kingdom of God) is present. It can only be your future if you have received the gift of recognition and you "reach out and grab" further nourishment while it is offered. The Truth can be retained (without significant dilution) only as one is physically connected with the Next Level, through an Older Member, and that relationship requires sustained, constantly upgraded perception and behavior.
            Humans of this civilization have periodically been given laws by the Next Level to upgrade their behavior. For example, the laws given to Moses were elementary "commandments" designed to make order and to raise the standards of a very "young" (primitive, barbaric) society. Then some 2000 years later, the Level Above Human, through Jesus' teachings, brought major updates (far more demanding): the greatest commandment is to "Love the Lord thy God with all thy heart, with all thy soul, and with all thy mind" (Matthew 22:37) - "If anyone comes to Me and does not hate his father and mother and his wife and children and brothers and sisters - and even his own life also - he cannot be My disciple" (Luke 14:26). Those wanting to go with Him had to do as He did. His teachings clearly spelled out the requirements (the actual formula) for making the literal and difficult transition from the human kingdom into the Kingdom Level Above Human.
            When a soul which has previously received the gift of life is awakened by its Older Member(s) in a particular incarnation or "season" (well after adolescence), it is picking up in its lessons where it left off at the end of its previous time with an Older Member. What any individual participates in prior to that "awakening" is of no real significance. If a soul had previously overcome such human characteristics as family ties and relationships, then just prior to its awakening, or rejoining with its Older Member, he is seen by those around him as suddenly becoming unstable, for he is compelled to once again separate from those imposing ties and seek to connect with what he had previously sought or connected with.
            <br></br><br></br><hr width ="100%" align = "center" size="1"></hr>
            <br></br> Now, at the close of this Age, every significant soul of this civilization has returned (and is to some degree in or attached to a physical body) to reap its reward. Its desires and attachments determine which heaven it is going to (by what it chooses to not overcome or what it clings to, and which "God" it looks to - one that increases its humanness or one that offers a way out of its humanness). Most who think they are for the true Kingdom of God are in fact working for the opposing side - the counterfeit "gods" - and will want to condemn us.
            <br></br><br></br><hr width ="100%" align = "center" size="1"></hr>
            <br></br> Today's leaders in the "industrialized world," though claiming to be democratic, self-righteously dictate to the rest of the world their own ideas of what are acceptable practices and behavior.
            <br></br>-- Money RULES! The monetary systems, through indebtedness, ownership, and insurance (all against God's ethic for man), bind man to servitude. The powers behind the money have discovered man's most tempting addictions, and through advertisement, movies, television, radio, and publications, feed these addictions with the excitement of sex, drugs (legal and illegal), and all manner of violence, to ensure their continued monetary power. Under the guise of "the social norm," this same world also imposes its distorted religious concepts and values. Their selfish pursuits corrupt and pollute the physical environment of all their "subjects" as well.
            <br></br>-- The pure information brought by every Representative sent by the Level Above Human is the same - total renunciation of the human world and human ways is required for entry into the true Kingdom of God. However, all religions that were originally based upon the information these Representatives brought have been targeted by major misinformation campaigns by the adversarial space races to the point that only a trace of the pure information remains in any of these religions' teachings and practices.
            <br></br>-- The true "Jews" - God's chosen people (the overcomers) - can no longer be found in a genetic strain - a race - or a religion.
            <br></br>-- The true "Israel" - where God's chosen people (the overcomers) reside - cannot be found in a geographical location.
            <br></br>-- The true "Christians" cannot be found among the religious who put human family values on the ultimate pedestal. They claim to know Jesus (Yeshua) as their "Messiah" or "Savior" - even though He never had a wife or children, nor would He accept as His disciple any who would not leave all attachments and ties to this world in order to learn from Him. Any truly committed to His family or God's ways, are today seen as "cults" and a threat to all of the above social norms and systems.
            <br></br><br></br><hr width ="100%" align = "center" size="1"></hr>
            <br></br> <br></br> The term "TRUE" Kingdom of God is used repeatedly because there are many space alien races that through the centuries of this civilization (and in civilizations prior) have represented themselves to humans as "Gods." We refer to them collectively as "space alien races in opposition to the Next Level," what historically have been referred to as "Luciferians," for their ancestors fell into disfavor with the Kingdom Level Above Human many thousands of years ago. They are not genderless - they still need to reproduce. They have become nothing more than technically advanced humans (clinging to human behavior) who retained some of what they learned while in the early training of Members of the Level Above Human, e.g., having limited: space-time travel, telepathic communication, advanced travel hardware (spacecrafts, etc.), increased longevity, advanced genetic engineering, and such skills as suspending holograms (as used in some so-called "religious miracles"). The Next Level - the true Kingdom of God - has the only truly advanced space-time travel vehicles, or spacecrafts, and is not interested in creating phenomena (signs) or impressive trickery.
            These malevolent space races are the humans' GREATEST ENEMY. They hold humans in unknown slavery only to fulfill their own desires. They cannot "create," though they develop races and biological containers through genetic manipulation and hybridization. They even try to "make deals" with human governments to permit them (the space aliens) to engage in biological experimentation (through abductions) in exchange for such things as technically advanced modes of travel - though they seldom follow through, for they don't want the humans of this civilization to become another element of competition. They war among themselves over the spoils of this planet and use religion and increased sexual behavior to keep humans "drugged" and ignorant (in darkness) while thinking they are in "God's" keeping. They use the discarnate (spirit) world to keep humans preoccupied with their addictions. These negative space races see to it, through the human "social norm" (the largest Luciferian "cult" there is), that man continues to not avail himself of the possibility of advancing beyond human.
            Just as the biological body is the "container" for the soul, the soul is the "container" for Mind ("Spirit"). Mind translates into the brain as information (knowledge). Information is available to humans from only two sources - the mind of the adversarial space races - or the Mind of the Kingdom Level Above Human. The mind of the adversarial space races yields misinformation (promoting the behavior and concepts of this corrupt world). The Mind from the true Kingdom of God yields true information (though the space races and their servants would reverse this interpretation). As we change, in the progression of overcoming humanness - the percentages change - of which mind occupies our soul - Truth increases as misinformation decreases. If one chooses to revert back to humanness, the process reverses - the Truth is aborted as the soul becomes more filled with mammalian mind. [The word "True" or "Truth" is defined as the most accurate perception available at any given level of understanding, changing at the level of the eye of the beholder.] That Next Level Truth can even be taken from us if we abuse it. When our "eye becomes single" or our soul is filled only with the Mind or "Spirit" from the true Kingdom of God, it becomes pure or "Holy" Mind ("Spirit").
            The design of the true Kingdom of God permits the presence of an adversial element during a human civilization as the primary catalyst for growth. Without it, we would have no choices - our free will could not be exercised. Our right choices are what find us in alignment to receive a "deposit" of recognition when the Truth is offered.
            <br></br><br></br><hr width ="100%" align = "center" size="1"></hr>
            <br></br> <br></br> Many say they live only for the "Harvest Time" - the "Last Days" - the "Second Coming." These have all arrived! There are souls - some of you, here now - who have received a deposit of recognition, and that knowledge finds you desirous of connecting and bonding with the Next Level. Those who have that deposit of Life will believe what we say, and know who we are. If they continue in that belief - sustain that Life (though the opposing space alien races will do anything to prevent them from nurturing that gift) they will be protected and "saved" from the approaching recycling and "spading under" of the civilization. They will have nothing to fear, nor will they know DEATH - even if they lose their human body. That continued belief will one day find them a member in the Level Above Human, in a physical body belonging to the true Kingdom of God - the Evolutionary Level Above Human - leaving behind this temporal and perishable world for one that is everlasting and non-corruptible.
            The design of the true Kingdom of God permits the presence of an adversial element during a human civilization as the primary catalyst for growth. Without it, we would have no choices - our free will could not be exercised. Our right choices are what find us in alignment to receive a "deposit" of recognition when the Truth is offered.
            <br></br><br></br><hr width ="100%" align = "center" size="1"></hr>
            - Today's Next Level Crew


                        </p>




            </div>
        </>
    );
}